# Generated by Django 4.2.26 on 2025-11-27 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta', max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del socio/cliente/proveedor', max_length=200)),
                ('es_proveedor', models.BooleanField(default=False, help_text='¿Es proveedor? (Ej: Duff)')),
                ('saldo_deuda', models.DecimalField(decimal_places=2, default=0.0, help_text='Cuenta pendiente (la deuda de Homer)', max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Socio (Cliente/Proveedor)',
                'verbose_name_plural': 'Socios',
                'ordering': ['nombre'],
            },
        ),
    ]
