# Generated by Django 4.2.26 on 2025-11-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(help_text='Dirección de facturación', max_length=500)),
                ('cliente', models.CharField(help_text='Nombre del cliente', max_length=200)),
                ('vendedor', models.CharField(help_text='Nombre del vendedor', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_dinero', models.DecimalField(decimal_places=2, help_text='Cantidad en formato decimal (ej: 1234.56)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
