# Generated by Django 4.2.26 on 2025-11-27 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True, help_text='Fecha del pedido')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado')], default='borrador', max_length=20)),
                ('proveedor', models.ForeignKey(help_text='Proveedor', limit_choices_to={'es_proveedor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='core.socio')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.CreateModel(
            name='LineaOrdenCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad (Ej. 10 barriles)')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='purchases.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'verbose_name': 'Línea de Orden de Compra',
                'verbose_name_plural': 'Líneas de Órdenes de Compra',
            },
        ),
    ]
