# Generated by Django 4.2.7 on 2025-12-01 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('invoicing', '0002_alter_pago_metodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='YourCompany', max_length=200)),
                ('direccion_linea1', models.CharField(default='8000 Marina Blvd. Suite 300', max_length=200)),
                ('direccion_linea2', models.CharField(default='94005 Brisbane', max_length=200)),
                ('direccion_linea3', models.CharField(default='California', max_length=200)),
                ('direccion_linea4', models.CharField(default='España', max_length=200)),
                ('direccion_facturacion_nombre', models.CharField(default='Gemini Furniture. Soham Palmer', max_length=200)),
                ('direccion_facturacion_linea1', models.CharField(default='Via Industria 21', max_length=200)),
                ('direccion_facturacion_linea2', models.CharField(default='Serravalle 47899', max_length=200)),
                ('direccion_facturacion_linea3', models.CharField(default='San Marino', max_length=200)),
                ('telefono_facturacion', models.CharField(default='(379)-167-2040', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_ciudad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_identificacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_orden',
            field=models.CharField(blank=True, help_text='Número de orden (ej: S00007)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tasa_impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de impuesto', max_digits=5),
        ),
        migrations.AddField(
            model_name='factura',
            name='vendedor',
            field=models.CharField(blank=True, default='Mitchell Admin', max_length=200),
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_producto', models.CharField(blank=True, help_text='Código del producto (ej: FURN 6667)', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción del producto/servicio')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_impuesto', models.DecimalField(decimal_places=2, default=0.0, help_text='% de impuesto', max_digits=5)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Cantidad × Precio unitario', max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='invoicing.factura')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Factura',
                'ordering': ['id'],
            },
        ),
    ]
