# Generated by Django 4.2.26 on 2025-11-27 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_sesion', models.CharField(blank=True, help_text='Referencia externa de sesión', max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pagado', 'Pagado'), ('fiado', 'Fiado/Deuda')], default='borrador', max_length=20)),
                ('almacen', models.ForeignKey(blank=True, help_text='Almacén desde donde se vende', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.almacen')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pos', to='core.socio')),
            ],
            options={
                'verbose_name': 'Orden POS (Ticket de Venta)',
                'verbose_name_plural': 'Órdenes POS',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LineaOrdenPOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad')),
                ('precio_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pos.ordenpos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'verbose_name': 'Línea de Orden POS',
                'verbose_name_plural': 'Líneas de Órdenes POS',
            },
        ),
    ]
