# Generated by Django 4.2.26 on 2025-11-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpos',
            name='sesion_mesa',
            field=models.ForeignKey(blank=True, help_text='Sesión de mesa asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='mesas.sesionmesa'),
        ),
    ]
