# Generated by Django 4.2.26 on 2025-11-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_ordenpos_sesion_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpos',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], help_text='Método de pago utilizado', max_length=20, null=True),
        ),
    ]
