# Generated by Django 4.2.26 on 2025-12-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_ordenpos_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaordenpos',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario en el momento de la venta', max_digits=10),
        ),
    ]
