# Generated by Django 4.2.26 on 2025-12-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_lineaordenpos_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaordenpos',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario en el momento de la venta', max_digits=10, null=True),
        ),
    ]
