# Generated by Django 4.2.26 on 2025-11-27 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(help_text='Número de la mesa', unique=True)),
                ('capacidad', models.IntegerField(default=4, help_text='Número de personas')),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='libre', max_length=20)),
                ('posicion_x', models.IntegerField(default=0, help_text='Posición X en el plano')),
                ('posicion_y', models.IntegerField(default=0, help_text='Posición Y en el plano')),
                ('forma', models.CharField(choices=[('cuadrada', 'Cuadrada'), ('redonda', 'Redonda'), ('rectangular', 'Rectangular')], default='cuadrada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SesionMesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_personas', models.IntegerField(default=1, help_text='Número de comensales')),
                ('hora_apertura', models.DateTimeField(auto_now_add=True)),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre la sesión')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_mesa', to='core.socio')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='mesas.mesa')),
            ],
            options={
                'verbose_name': 'Sesión de Mesa',
                'verbose_name_plural': 'Sesiones de Mesa',
                'ordering': ['-hora_apertura'],
            },
        ),
    ]
